// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.1
// source: httpx.proto

package httpxcommons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId int64  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success   bool   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Payload   []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PBResponse) Reset() {
	*x = PBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httpx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBResponse) ProtoMessage() {}

func (x *PBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_httpx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBResponse.ProtoReflect.Descriptor instead.
func (*PBResponse) Descriptor() ([]byte, []int) {
	return file_httpx_proto_rawDescGZIP(), []int{0}
}

func (x *PBResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PBResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PBResponse) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PBResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PBResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_httpx_proto protoreflect.FileDescriptor

var file_httpx_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68,
	0x74, 0x74, 0x70, 0x78, 0x22, 0x8d, 0x01, 0x0a, 0x0a, 0x50, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x78, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_httpx_proto_rawDescOnce sync.Once
	file_httpx_proto_rawDescData = file_httpx_proto_rawDesc
)

func file_httpx_proto_rawDescGZIP() []byte {
	file_httpx_proto_rawDescOnce.Do(func() {
		file_httpx_proto_rawDescData = protoimpl.X.CompressGZIP(file_httpx_proto_rawDescData)
	})
	return file_httpx_proto_rawDescData
}

var file_httpx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_httpx_proto_goTypes = []interface{}{
	(*PBResponse)(nil), // 0: httpx.PBResponse
}
var file_httpx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_httpx_proto_init() }
func file_httpx_proto_init() {
	if File_httpx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_httpx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_httpx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_httpx_proto_goTypes,
		DependencyIndexes: file_httpx_proto_depIdxs,
		MessageInfos:      file_httpx_proto_msgTypes,
	}.Build()
	File_httpx_proto = out.File
	file_httpx_proto_rawDesc = nil
	file_httpx_proto_goTypes = nil
	file_httpx_proto_depIdxs = nil
}
