// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: httpx.proto

package httpxcommons

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PBResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            int64    `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBResponse) Reset()         { *m = PBResponse{} }
func (m *PBResponse) String() string { return proto.CompactTextString(m) }
func (*PBResponse) ProtoMessage()    {}
func (*PBResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d1d671f8675ea7f, []int{0}
}
func (m *PBResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBResponse.Unmarshal(m, b)
}
func (m *PBResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBResponse.Marshal(b, m, deterministic)
}
func (m *PBResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBResponse.Merge(m, src)
}
func (m *PBResponse) XXX_Size() int {
	return xxx_messageInfo_PBResponse.Size(m)
}
func (m *PBResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBResponse proto.InternalMessageInfo

func (m *PBResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PBResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PBResponse) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *PBResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PBResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*PBResponse)(nil), "httpx.PBResponse")
}

func init() { proto.RegisterFile("httpx.proto", fileDescriptor_2d1d671f8675ea7f) }

var fileDescriptor_2d1d671f8675ea7f = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x28, 0x29, 0x29,
	0xa8, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x7a, 0x19, 0xb9, 0xb8,
	0x02, 0x9c, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf3,
	0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc,
	0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48,
	0x96, 0x8b, 0xab, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x24, 0x3e, 0x33, 0x45, 0x82, 0x19, 0xac,
	0x87, 0x13, 0x2a, 0xe2, 0x99, 0x02, 0xd2, 0x58, 0x5c, 0x9a, 0x9c, 0x9c, 0x5a, 0x5c, 0x2c, 0xc1,
	0xa2, 0xc0, 0xa8, 0xc1, 0x11, 0x04, 0xe3, 0x82, 0x64, 0x0a, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53,
	0x24, 0x58, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x27, 0xbe, 0x28, 0x1e, 0xb0, 0xc3, 0x92,
	0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x8a, 0x93, 0xd8, 0xc0, 0xae, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x65, 0xb2, 0x63, 0xa6, 0xbc, 0x00, 0x00, 0x00,
}
