kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

workspace:
  base: /root/drone-go
  path: src/git.xiagaogao.com/coffee/httpx

steps:
  - name: build
    environment:
      GOPROXY: https://goproxy.io
      GOPRIVATE: git.xiagaogao.com
      GOSUMDB: sum.golang.google.cn
    commands:
      - echo $USERNAME $PASSWORD
      - cat /root/.netrc >> ~/.netrc
      - ln -s /root/.gitconfig ~/.gitconfig
      - go mod tidy
    when:
      branch:
        include:
          - feature/*
          - master
          - dev
      event:
        include:
          - push
          - pull_request
